using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServicePulseMonitor.Common;
using ServicePulseMonitor.Data;
using ServicePulseMonitor.Data.DTOs;

namespace ServicePulseMonitor.Controllers;

/// <summary>Provides read access to service alerts generated by the health monitoring pipeline.</summary>
[ApiController]
[Route("api/alerts")]
public class AlertsController(
    ServicePulseDbContext db,
    ILogger<AlertsController> logger) : ControllerBase
{
    /// <summary>
    /// Get a paginated list of alerts, optionally filtered by service and resolution status.
    /// </summary>
    /// <param name="serviceId">Filter to alerts for a specific service ID.</param>
    /// <param name="isResolved">Filter to open (<c>false</c>) or resolved (<c>true</c>) alerts.</param>
    /// <param name="pageNumber">Page number (default: 1).</param>
    /// <param name="pageSize">Page size (default: 20, max: 100).</param>
    /// <returns>Paged list of alerts ordered by <c>TriggeredAt</c> descending.</returns>
    /// <response code="200">Alerts retrieved successfully.</response>
    /// <response code="400">Invalid pagination parameters.</response>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<AlertDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<AlertDto>>> GetAlerts(
        [FromQuery] long? serviceId = null,
        [FromQuery] bool? isResolved = null,
        [FromQuery] int pageNumber = 1,
        [FromQuery] int pageSize = 20)
    {
        if (pageNumber < 1)
            return Problem(detail: "Page number must be >= 1", statusCode: 400);

        if (pageSize < 1 || pageSize > 100)
            return Problem(detail: "Page size must be between 1 and 100", statusCode: 400);

        var query = db.Alerts.Include(a => a.Service).AsNoTracking();

        if (serviceId.HasValue)
            query = query.Where(a => a.ServiceId == serviceId.Value);

        if (isResolved.HasValue)
            query = query.Where(a => a.IsResolved == isResolved.Value);

        var totalCount = await query.CountAsync();

        var alerts = await query
            .OrderByDescending(a => a.TriggeredAt)
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .Select(a => new AlertDto
            {
                AlertId = a.AlertId,
                ServiceId = a.ServiceId,
                ServiceName = a.Service.ServiceName,
                AlertType = a.AlertType,
                TriggeredAt = a.TriggeredAt,
                IsAcknowledged = a.IsAcknowledged,
                IsResolved = a.IsResolved,
                ResolvedAt = a.ResolvedAt,
                Message = a.Message != null ? a.Message.RootElement.GetRawText() : null
            })
            .ToListAsync();

        logger.LogInformation("Retrieved {Count} alerts (page {Page})", alerts.Count, pageNumber);

        return Ok(new PagedResult<AlertDto>
        {
            Items = alerts,
            TotalCount = totalCount,
            PageNumber = pageNumber,
            PageSize = pageSize
        });
    }
}
