// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicePulseMonitor.Data;

#nullable disable

namespace ServicePulseMonitor.Data.Migrations
{
    [DbContext(typeof(ServicePulseDbContext))]
    [Migration("20260131060757_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServicePulseMonitor.Models.Alert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AlertId"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alert_type");

                    b.Property<bool>("IsAcknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_acknowledged");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<JsonDocument>("Message")
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("triggered_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.HasKey("AlertId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TriggeredAt");

                    b.HasIndex("UserGuid");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.AlertRule", b =>
                {
                    b.Property<long>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RuleId"));

                    b.Property<string>("LogType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("log_type");

                    b.Property<string>("NotificationChannel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_channel");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_type");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("threshold");

                    b.HasKey("RuleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.HealthCheck", b =>
                {
                    b.Property<long>("HealthCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("health_check_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("HealthCheckId"));

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("HealthCheckId");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.ToTable("health_checks", null, t =>
                        {
                            t.HasCheckConstraint("CK_HealthCheck_Status", "status IN ('Healthy', 'Degraded', 'Unhealthy')");
                        });
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.NotificationConfig", b =>
                {
                    b.Property<Guid>("NotificationConfigGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_config_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<string>("Uri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("uri");

                    b.HasKey("NotificationConfigGuid");

                    b.HasIndex("RuleId");

                    b.ToTable("notification_configs", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.Service", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ServiceId"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("ServiceName")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.ServiceDependency", b =>
                {
                    b.Property<long>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dependency_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DependencyId"));

                    b.Property<long>("DependsOnServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on_service_id");

                    b.Property<DateTime>("DiscoveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("discovered_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("DependencyId");

                    b.HasIndex("DependsOnServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_dependencies", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserGuid");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.Alert", b =>
                {
                    b.HasOne("ServicePulseMonitor.Models.Service", "Service")
                        .WithMany("Alerts")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicePulseMonitor.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.AlertRule", b =>
                {
                    b.HasOne("ServicePulseMonitor.Models.Service", "Service")
                        .WithMany("AlertRules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.HealthCheck", b =>
                {
                    b.HasOne("ServicePulseMonitor.Models.Service", "Service")
                        .WithMany("HealthChecks")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.NotificationConfig", b =>
                {
                    b.HasOne("ServicePulseMonitor.Models.AlertRule", "AlertRule")
                        .WithMany("NotificationConfigs")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.ServiceDependency", b =>
                {
                    b.HasOne("ServicePulseMonitor.Models.Service", "Callee")
                        .WithMany("CallingServices")
                        .HasForeignKey("DependsOnServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicePulseMonitor.Models.Service", "Caller")
                        .WithMany("CalledServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Callee");

                    b.Navigation("Caller");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.AlertRule", b =>
                {
                    b.Navigation("NotificationConfigs");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.Service", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Alerts");

                    b.Navigation("CalledServices");

                    b.Navigation("CallingServices");

                    b.Navigation("HealthChecks");
                });

            modelBuilder.Entity("ServicePulseMonitor.Models.User", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
